### ISSUE TITLE
Reviewing offers

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#128]
Learn more about improvement proposals: https://bit.ly/2xLJT3R

## Impacted areas:

- [x] Design
- [x] Code
- [ ] Infrastructure
- [x] Users
- [ ] Finances
- [ ] Processes

## Current situation
When a provider adds an offer to the webshop, a sponsor can only accept / deny, but does not have any ways to review the offer and ask for changes like updating the picture or texts.

## Desired situation
Allow the sponsor to ask the provider for improvements

(to discuss with stakeholders) Allow the sponsor to set an end-date for a validation

## Plan
https://www.figma.com/file/6tNxXmZrflGwNzQsR3EyKT/Reviewing-offers?node-id=1%3A23

## Task
- [ ] Create figma prototype @danrminds @sashooa
- [ ] Review figma prototype @dev-rminds @jamalv @maxvisser 
- [ ] Start development @dev-rminds

**Comment by maxvisser** [comment]
https://www.figma.com/file/1Kxo3w0U7HY8eICtcbKFQL/Provider-enhancement?node-id=58%3A15

**Comment by danrminds** [comment]
This one is already in development and almost production ready. At what stage should we close an IP? Options:
- When is planned
- When is in development
- When is in staging and ready 
- When is in production

**Comment by jamalv** [comment]
@danrminds I like when in production :D
