### ISSUE TITLE
Change "100%" discount to "Free"

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#172]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Daniëlle in Figma: https://www.figma.com/file/LOei9CO8mj4lshcCHQvTBz?node-id=23:42#24539380

### Change description
Right now when there is 100% discount on a product on the webshop, we are displaying it as "100% discount" - This is quite unnatural and it would be better to display it as "Free" or in dutch - Gratis

## Impacted areas:

- [ ] Design
- [ ] Code
- [ ] Infrastructure
- [ ] Users
- [ ] Finances
- [ ] Processes

## Current situation
Offers need to cost a minimum of 20ct

## Desired situation
Offers should be able to be free

## Tasks
- [ ] Me app designs need to be updated
- [ ] Voucher page transaction block needs to be updated
- [ ] Forus modal for checkout needs to be updated

**Comment by maxvisser** [comment]
100% korting is currently not available as a feature.

**Comment by jamalv** [comment]
Ah yes, then I think maybe we should add that to the change request, als being able to do 100% discount is part of a tender. Maybe we should add a checkbox for the provider "This offer is free?"

So then the offer needs to be either free, or more expensive than 20ct to cover the transaction costs?

**Comment by maxvisser** [comment]
Do these products need to be reserved (does a product voucher need to be created)

**Comment by jamalv** [comment]
I would say yes. This way a provider can set a maximum inventory for the offer if there is a limit.

**Comment by maxvisser** [comment]
Ah ok; I would just start without reservations as it is a pretty simple fix. I could not find it in the tender maybe you can point it out to me so I can read aswell how it is described there;

**Comment by jamalv** [comment]
Aah yea, for reservations we would need to update the apps as well I imagine?

**Comment by jamalv** [comment]
Sent you a DM about the tender 👍

**Comment by maxvisser** [comment]
> Aah yea, for reservations we would need to update the apps as well I imagine?
well it looks a bit weird alot of these zero transactions;

**Comment by jamalv** [comment]
Yea, so we also need to have a look at how this would impact the app. If we make this an improvement proposal we can implement this in phases? First without reservations, and then also with reservations?

**Comment by maxvisser** [comment]
Yes I think having it without reservation is already pretty nice. Also: I would first enhance the way product stocks work before adding more things that depend on it; https://github.com/teamforus/general/issues/136

**Comment by maartenfv** [comment]
I just spoke with another project besides Groningen and they want this feature as well. I would like to upvote this one :).

**Comment by maartenfv** [comment]
@jamalv @maxvisser Coul you give a status update on this issue?

**Comment by maxvisser** [comment]
Issue is planned to start work on concept, design, development starting next week. As limiting offers/discounts actions will become more of how it will work we can look on how to implement this. Currently working on Children/New Offers/Reactivating old cards

**Comment by maxvisser** [comment]
@jamalv could you start on making an improvement proposal? Whats needed.

**Comment by jamalv** [comment]
@maxvisser I made a Figma proposal here: https://www.figma.com/file/aRfkoe4wr2B4Wz8XVIaUa5/Free-offers?node-id=1%3A86

The provider should be able to offer a product/service for free > then it should appear as free in the webshop. ("Gratis")

**Comment by maxvisser** [comment]
Probably include the Sponsor and Me scanning parts aswell.

**Comment by maxvisser** [comment]
As our current system expects each transaction created to be payed out by bunq (no exceptions) I  would estimate this issue on scope difficulty. You need to somehow implement it that you can allow 0 euro transactions without paying them out. Not sure on the difficulty. Probably dev-rminds needs to do this.

**Comment by jamalv** [comment]
@maxvisser I'm a bit stuck on this issue. It's a must-have and I cannot really oversee what needs to happen. Could you help me out a bit? Maybe we need to have a separate discussion about it?

**Comment by jamalv** [comment]
By the way, in the context of actions I don't expect there to be a transaction at all, right? So could this at least be implemented in actions?

**Comment by maxvisser** [comment]
There will be a transaction (from sponsor to provider)

**Comment by jamalv** [comment]
Discussed this with max. This will be part of actions. When a product if fully subsidized, it will be displayed as free.

**Comment by maxvisser** [comment]
We make it possible approve a product (create a subsidy) with a 0 contribution; there will be 0 euro transaction. We will not send any of this information to bunq

**Comment by maxvisser** [comment]
Task is created:
https://github.com/teamforus/forus/issues/1729
