### ISSUE TITLE
Reactivate physical cards

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#182]
Learn more about improvement proposals: https://bit.ly/2xLJT3R

## Impacted areas:

- [x] Design
- [x] Code
- [x] Infrastructure
- [x] Users
- [x] Finances
- [x] Processes

## Current situation
The current system of Stadjerspas is now used for almost 5 years. The current QR-codes will get invalid when we start using Forus. There ~ 16000 old passes in circulation and 1573 in stock at the printer; 

A user can open his QR:
* on the webshop
* in their email
* as a printable
* in the app

## Desired situation
The main objective of this scenario is that the old passes do not have to be thrown away, but can be reused after migration to Forus. The resident must link the pass to the new system for this. This way we can minimize waste.

## Plan
Watch the explainer video here: https://drive.google.com/file/d/1OxR9uEjTWuV7eKrOCkHUc4PKqtpwg7EQ/view?usp=sharing

Userflow:
1. The municipality communicates that the Stadjerspas is being renewed. The old city pass and the associated apps will expire on [date] and residents must apply for a new digital pass. 
2. Current providers are informed well before the old system goes offline, and are requested to digitally register for the new system.
3. On the date of going live, the old apps stop working, they can be removed, and the old ones can no longer be scanned. The resident is requested to apply for a new digital pass online.
4. The citizen requests fund digitally with DigiD. The previously known citizen has the new pass within minutes. The “unknown” residents are assessed by the municipality and receive the digital pass immediately after assessment.
5. As soon as the resident has registered and obtained the new digital pass, we offer the resident the opportunity to link the old pass to the new system and the new voucher. 

Advantages:
- Old passes can be reused and do not need to be thrown away. This applies to existing passes that are in circulation and to passes that are still at the printer's. This is in line with the sustainability objectives of the municipality.
- The current card stock at the printer (1600 cards) ensures that no new cards need to be developed yet. Especially since fewer passes (currently 50 per week) are expected to be applied for..
- The municipality has the ambition to replace physical passes as much as possible by a digital pass because it is more flexible towards the future.
Disadvantages:
- Forus uses a different type of QR code and, forcan security reasons, not continue to support the Stadjerspas QR code in the long term, especially when more things (such as multiple credits, the waste card and perhaps identification data) are linked to the pass. This solution is therefore temporary and not future-proof. 

### Supporting old cards figma prototype:
https://www.figma.com/file/vnpp2wD8h66vMKuYuQMNgK/%F0%9F%94%B5Old-cards?node-id=0%3A1

## Figma prototype review
- [x] Design @danrminds @sashooa 
- [x] Text @linda-90 @maartenfv 
- [ ] Accessibility @GerbenBosschieter 
- [x] Technical review and add tasks to this epic @danrminds

**Comment by maxvisser** [comment]
Moved the deadline for this IP as their is strategy yet / direction to go

**Comment by jamalv** [comment]
@maxvisser this proposal is at the stakeholders for approval. 

We can now start reviewing the prototype and dev issues can be created.

Could you discuss this epic with @danrminds and start breaking it up into seperate dev tasks? It would be nice if this week the figma prototype review can be done so that the development can be planned asap.

@GerbenBosschieter would you have the possibility to do an accessibility (/risk) review somewhere this week?

**Comment by maxvisser** [comment]
I would first start with functional design and creating the high fidelity prototype.

**Comment by jamalv** [comment]
Yea, I think creating the high fidelity prototype is part of the epic :)

What do you mean with functional design?

**Comment by maxvisser** [comment]
With functional design I mean thinking about each; what needed for it to function.

**Comment by GerbenBosschieter** [comment]
@jamalv I will take a look at it for analysing the risk and accessibility review

**Comment by maxvisser** [comment]
## Functional design

### User stories
1. As a requester I want to have a button on my vouchers page to assign or request a physical card.

__Acceptance criteria__
- The button to connect a card should be visible both on Desktop / Mobile
- Button should only be visible on Groningen implementation webshop
- An highlighted popup which makes a CTA to the user for assigning a existing physical card.

2. **As a requester I want to assign a existing physical card number to a voucher**

__Acceptance criteria__
- Atleast 8 numbers are needed to complete the form
- An error should occur when a number is used "Deze pascode is al ingebruik'
- Input fields should work on Internet explorer
- Input fields should work on tablets. Keyboard should open
- Input field should be visible and working on mobile screens. It should be responsive

3. As a requester I want to order a new physical card that get send to my address.

__Acceptance criteria__
- The form should require atleast postalcode and housenumber to function
- All data filled in the form should emailed to xx@xx.nl (@jamalv did we already have a talk about this with DCP?)
- A user can order a card xx times (do we need to store that a user ordered a card for a voucher?)
- Should the requester get a order confirmation on his mail/notification log?

## Scenario: Assigning a voucher to existing physical card

### Pre-conditions

1. A requester with an active voucher
2. User logged in on Groningen implementation
3. A provider which is allowed to scan the budget voucher

### Input data

1. Physical card code
    * unique number

### Prerequisites

1. A voucher
2. In possession of a physical card

### Instructions

<table>
<tr><th>Step No.</th><th>Step description</th><th>Expected result</th></tr>
<tr><td>1.</td><td>Go to the webshop and begin by clicking on <b>Mijn vouchers<b></td><td>A new page opens with the voucher list.</td></tr>
<tr><td>2.</td><td>Click on the voucher you want to assign to a physical card.</td><td>The voucher page opens of the voucher you selected.</td></tr>
<tr><td>3.</td><td>On voucher page, click on the physical card button</td><td>A modal opens which should display a choice between assigning a card and ordering a new one.</td></tr>
<tr><td>4.</td><td>Choose assigning a card</td><td>A new model screen opens with the option to fill in 8 numbers.</td></tr>
<tr><td>5.</td><td>Fill in 8 numbers on the physical card into the input field and press submit.</td><td>The model should transition to a success screen when 8 numbers are assigned to the voucher.</td></tr>
<tr><td>6.<td>Scan QR-code with Me-app as a provider which is allowed to scan this voucher</td><td>A transaction screen opens in Me-app which indicates the QR-code is working.</td></tr>
</table>

## Scenario: Ordering a new physical card

### Pre-conditions

1. A requester with an active voucher
2. User logged in on Groningen implementation

### Input data

1. Physical card code
    * unique number

### Prerequisites

1. A voucher

### Instructions

<table>
<tr><th>Step No.</th><th>Step description</th><th>Expected result</th></tr>
<tr><td>1.</td><td>Go to the webshop and begin by clicking on <b>Mijn vouchers<b></td><td>A new page opens with the voucher list.</td></tr>
<tr><td>2.</td><td>Click on the voucher you want to assign to a physical card.</td><td>The voucher page opens of the voucher you selected.</td></tr>
<tr><td>3.</td><td>On voucher page, click on the physical card button</td><td>A modal opens which should display a choice between assigning a card and ordering a new one.</td></tr>
<tr><td>4.</td><td>Choose ordering a card</td><td>A new model screen opens with the option to order a card.</td></tr>
<tr><td>5.</td><td>Press the button 'BESTELLEN', two input fields will apear which the userfills in and he presses submit.</td><td>The model should transition to a success screen which indicates the card has been ordered.</td></tr>
</table>

**Comment by danrminds** [comment]
@maxvisser @jamalv 

Is there any rule applicable to the 16-digits codes from the current cards?
Would be nice to implement at least some type of validation. 

Example: 
- Not containing 8
- Starting with 10
- etc.

**Comment by jamalv** [comment]
Yes, I just checked. All cards start with "1001" so only the last 8 digits have to be unique.

So the way we implemented in figma, can be the way it is implemented for real:

<img width="312" alt="Screenshot 2020-07-05 at 17 07 24" src="https://user-images.githubusercontent.com/30194799/86535645-10163a80-bee2-11ea-9844-78737c6fee22.png">

Side note: at these kind of fields a blinking cursor is very important, otherwise people dont understand that they can start typing, i've seen many people struggle with this already :)

**Comment by danrminds** [comment]
@maxvisser @jamalv 

Also - let's discuss how we handle the ordering of new cards?

1. Where do we display those orders? In the sponsor dashboard? or in any other place? 
2. At what stage is the code of the new card connected? Is this code automatically generated or not? Or the code is already on the cards? Is this something the sponsor will do from the list of orders? Or the citizen has to do it himself after he get's it in the post?

**Comment by jamalv** [comment]
1. The ordering of new cards will be by email. We will send an email to the printer with the order details. (postalcode + house number).

2. The printer already has 1600 pre-printed cards - they have the codes already on them. So yes, it's the last option, the citizen has to do it themselves, the instructions are in the included letter.

**Comment by danrminds** [comment]
> 1. The ordering of new cards will be by email. We will send an email to the printer with the order details. (postalcode + house number).
We will need an exact formatting for the email. When you have time - please check that with them.

**Comment by danrminds** [comment]
Another question - 
Will we need any validation for the postcode and house number?

Possible:
 - Simple format validation (4 digits + 2 letters)
 - Validation from a list of allowed postcodes
 - Validation via an API - that this postcode and house number exist.

**Comment by jamalv** [comment]
Depends on the scope. Simple format validation is a no brainer, so yes please :)

Next, only people in the municipality of Groningen should be able to order this card. I don't know if we already have a dependancy which we can use to check this. Do you already have experience with dependancies for checking this?

**Comment by jamalv** [comment]
I have also added a couple comments for you in Figma:

New acceptance criteria: any input field should have a blinking cursor so people know they can start typing (you would be surprised how much it confuses people if there is none - they just keep clicking on the field, often selecting the whole page), comment: https://www.figma.com/file/vnpp2wD8h66vMKuYuQMNgK?node-id=5:2335#30178765

I think this can also help avoid some confusion: https://www.figma.com/file/vnpp2wD8h66vMKuYuQMNgK?node-id=5:2335#32105975

And just being a bit picky on the design: https://www.figma.com/file/vnpp2wD8h66vMKuYuQMNgK?node-id=378:4572#32105986 and https://www.figma.com/file/vnpp2wD8h66vMKuYuQMNgK?node-id=4:1921#32106016

**Comment by jamalv** [comment]
As I understand this still needs to be fixed on mobile? @maxvisser @danrminds is that correct?

**Comment by maxvisser** [comment]
Yes created a task for mobile design in Forus repo

**Comment by maxvisser** [comment]
This is in release v0.15.0

**Comment by maartenfv** [comment]
@maxvisser What is the policy? Should the issue be closed when released or when developed or tested or when?

**Comment by maxvisser** [comment]
When it's on production

**Comment by maxvisser** [comment]
released
