### ISSUE TITLE
Finalize provider signupflow v2

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#221]
### User stories

As Forus I would like to use this sign up flow for the project-100 implementation so that we can leave behind the old sign up flow.

### Current Links
production: https://forus.io/provider/sign-up
staging: https://staging.forus.io/provider/sign-up-v2

### Figma

[Link to Figma](https://www.figma.com/file/qH0keMD7Pe3kjxx5BI0WR4/Signupflow-v2-texts?node-id=0%3A1)

### Definition of done of this issue
The link from the signup V2 needs be default and the old V1 needs to go offline.

**Comment by maartenfv** [comment]
- [ ] Needs text review
- [ ] Needs final design review
- [ ] Needs approval from @GerbenBosschieter 
- [ ] Needs approval from @linda-90 
- [ ] Needs plan on how to take down the old version @jamalv @maxvisser 
- [ ] Needs to be presented to Stakeholders project-100 @linda-90

**Comment by jamalv** [comment]
- [ ] https://github.com/teamforus/general/issues/219

**Comment by maartenfv** [comment]
https://github.com/teamforus/forus/issues/1566

**Comment by jamalv** [comment]
New figma link specifically for this: https://www.figma.com/file/qH0keMD7Pe3kjxx5BI0WR4/Signupflow-v2-texts?node-id=0%3A1

**Comment by maxvisser** [comment]
Gerben made a bunch of issues

**Comment by jamalv** [comment]
@maxvisser linda also did a text review, therefore a final check on texts would be useful: https://www.figma.com/file/qH0keMD7Pe3kjxx5BI0WR4/%F0%9F%94%B5Signupflow-v2-texts?node-id=1%3A2650

**Comment by jamalv** [comment]
@dev-rminds @maxvisser @danrminds we would like to release this asap, could the final fixes therefore be branched from master?

**Comment by jamalv** [comment]
@maxvisser these are the final texts: https://www.figma.com/file/qH0keMD7Pe3kjxx5BI0WR4/%F0%9F%92%BBSignupflow-v2-texts

**Comment by maartenfv** [comment]
discussed with @maxvisser has new issues. @GerbenBosschieter Have these issues all been made and added to this epic?

**Comment by jamalv** [comment]
@GerbenBosschieter I believe we fixed a few things two releases ago; are there still things needed to be fixed before we go live with the next client?
