### ISSUE TITLE
CRUD in Webshop

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#270]
## Current situation
We have records in the me app: https://www.figma.com/file/Dyk8ACF91stjmWmO3rUpXv/?node-id=1098%3A11364

## Desired situation
Add records to the webshop as well

## Plan
Figma (brainstorm): https://www.figma.com/file/72RtRfLFzzzLaN92EtJwxS/?node-id=1%3A23

**Comment by maartenfv** [comment]
We need the Figma designs to be updated. 
Could you tell a bit more about the context of this issue?

**Comment by jamalv** [comment]
Ah; missed this one - yes; we're pretty far with the mobile apps; now this is on my radar again will work to advance this furter; will update this issue when next steps have been made.

**Comment by maxvisser** [comment]
Screenshots of webshop are in the Figma IP of Me CRUD

**Comment by jamalv** [comment]
@danrminds @maxvisser @jknnr @maxvisser @GerbenBosschieter 

I have invited you all to a brainstorm session this friday to talk about this issue. Please respond to the invitation to let us know if you will be there, and if anyone else might be interested in joining.

**Comment by jamalv** [comment]
### Results of the brainstorm:
We looked into the current status of the Me app and the Webshop.
We discussed what is currently possible with the API (for example regarding catagories)
We had some ideas about improving records
 - Add a pending status
 - Adding a search bar
 - Adding a "profile" part to the webhshop with all the settings/features as seperate pages and a menu
We had some discussion about how the feature will be used

### Strategy:
 - [ ] First do feature alignment between Webshop and Me app. (add all me app features to the webshop)
 - [ ] Write some specifications for how the records / validations will be used, and improve both the me app / webshop accordingly

### Task:
 - [ ] Create designs for Records in the me app (@maxvisser could you create this task for lena?)
 - [ ] Write specifications for how records will be used @jamalv (after I am back from holiday :))

**Comment by maxvisser** [comment]
I have made a new commit to atleast show records on webshop. Seemed like a great first step

**Comment by maxvisser** [comment]
@jamalv is this still a must have?
