### ISSUE TITLE
Validator dashboard: Add timestamps

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#319]
Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
Stakeholders

### Change description
This issue is to list some must have fixes for example from usertests to fix

- [ ] Add timestamps: https://www.figma.com/file/cHEYJrdU5hGz76pZNgsDkP/Adding-more-explicit-dates-to-validation-process?node-id=1%3A3306

**Comment by jamalv** [comment]
how to reach validator dashboard? add link to dropdown? other path?

**Comment by jamalv** [comment]
add carrot to dropdown 

![Screenshot 2020-07-30 at 09 14 09](https://user-images.githubusercontent.com/30194799/88892427-08c62080-d245-11ea-840f-9af3e573f589.png)

add validator to this dashboard

**Comment by jamalv** [comment]
- [ ]  expand attachments by default, people don't understand there are attachements
- [ ] Add search
- [ ] Add filters (maybe als filter on status, like at the funds page)

**Comment by maxvisser** [comment]
https://github.com/teamforus/general/issues/335 duplicate?

**Comment by maxvisser** [comment]
I see alot of these things are fixed but not all. I adjusted the issue to be specific about the timestamps.

**Comment by maxvisser** [comment]
@jamalv I am confused if I look at figma.. One page has time and dates other has time passed? which one is accurate?

**Comment by maxvisser** [comment]
Created an issue for expanding attachments by default https://github.com/teamforus/general/issues/429

**Comment by jamalv** [comment]
> @jamalv I am confused if I look at figma.. One page has time and dates other has time passed? which one is accurate?

@maxvisser I have no strong preference here; time passed would be nice if it is not to big of a scope. Otherwise a simple timestamp will do.

I think the figma proposal still needs design review though.

**Comment by maxvisser** [comment]
This is a duplicate of https://github.com/teamforus/general/issues/319

**Comment by maartenfv** [comment]
@jamalv as discussed with Margrieta en Marleen we need to have a way to keep an overview of old or expired messages. How does Margrieta keep track of messages send and the ones that are old?
What happens if somebody does not reply?
Can we resend the message?
Can we send reminder automatically naar inwoner. Uw verzoek staat nog open.

**Comment by maxvisser** [comment]
Currently there is no easy way to track these messages. Maybe a seperate page with all open 'clarification requests' would be nice feature. Aswell as allowing validators to send reminders. Could you open CR for these things or shall I?

**Comment by maartenfv** [comment]
@maxvisser That would be very nice if possible :)

**Comment by maxvisser** [comment]
released

**Comment by maartenfv** [comment]
What has been released?

**Comment by maxvisser** [comment]
What in figma on master
