### ISSUE TITLE
Signupflows MVP

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#32]
## Change request

Requested by: Customer

### Change description

Goal: Any role should be able to sign up for the platform.

Create / update signup flows for:
- Me app
- Provider
- Sponsor
- Requester
- Validator

## Phase 1: Analysis
Goal: Research if this change is desirable/feasable & what the impact would be.

This change would impact:
- [x] Design
- [x] Code
- [ ] Infrastructure
- [x] Users
- [ ] Finances
- [ ] Processes

Analysis tasks:
- [x] Research feasibility
- [ ] Perform risk assesment
- [ ] Need to inform users

Make decision
- [x] Go
- [ ] No Go

## Phase 2: Proposal
Goal: Make a concrete proposal for the change.

- [ ] Specifications
- [ ] Communciation plan
- [ ] Planning in time

Proposal of tasks:
- [ ] First update the provider signup flow
- [ ] Deploy it next to our current signup flow (/v2)
- [ ] Get feedback from our users, and improve
- [ ] Prototype MVP versions of other signup flows
- [ ] Review current status of requester flow
- [ ] Test and deploy other signup flows
- [ ] Decide when the new signupflow is better then the old one
- [ ] Create a manual entry about the new provider signup flow
- [ ] Create an instruction video about the new provider signup flow
- [ ] Send an email to the current providers, when we will update the flow, & where they can view the instruction video and manual

Make decision
- [ ] Go
- [ ] No Go

## Phase 3: Prototyping
Goal: Create high fidelity prototype for approval and developer handoff.

Scope: For all the flows the goal is to:
- [ ] Get an MVP into production
- [ ] Create a prototype for the "Should have" version

Figma links:
- [x] Me app: https://www.figma.com/file/sDB8jUy4fM4oIdlPTL90nf/Log-me-in?node-id=50%3A19
- [x] Provider MVP: https://www.figma.com/file/YluSZHDC1E80yRaHee1UE7/prototype-signupflows?node-id=22%3A0
- [ ] Sponsor MVP: https://www.figma.com/file/YluSZHDC1E80yRaHee1UE7/prototype-signupflows?node-id=108%3A1
- [ ] Validator MVP: https://www.figma.com/file/YluSZHDC1E80yRaHee1UE7/prototype-signupflows?node-id=108%3A1757
- [ ] Requester https://www.figma.com/file/YluSZHDC1E80yRaHee1UE7/prototype-signupflows?node-id=178%3A2174

Make decision
- [ ] Go
- [ ] No Go

## Phase 4: Development
Goal: Convert the prototype into code and add changes into the design library.

- [ ] Provider signup flow PR: https://github.com/teamforus/forus-frontend/pull/748
- [ ] Sponsor signup flow PR [not started]
- [ ] Validator signup flow PR [not started]
- [ ] Requester signup flow PR [not started]

Make decision
- [ ] Go
- [ ] No Go

## Phase 5: Staging
Goal: Add the new feature to an upcoming release and merge the changes into the design library

Release pull request link: 

- [ ] Merge into release branch and add to staging environment

## Phase 6: Testing
Goal: Ensure that the new feature is stable and does not break anything

- [ ] Run tests on staging environment
- [ ] Fix bugs if needed
- [ ] Revert merge if bugs not fixable for this release

## Phase 7: Release
Goal: Add the feature into production and inform users as planned in phase 2

- [ ] Inform users of (upcoming) change
- [ ] Release feature on a monday morning
