### ISSUE TITLE
Epic: Finalize Potjeswijzer

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#341]
## Context:

This thursday we have a presentation to the project group where we will show what we did with their feedback. After that we will continue user testing to keep gathering feedback from end users.

We would like to process as much feedback before thursday as possible!

This epic is to list/link required fixes for the Potjeswijzer webshop.

## Tasks

Must have:
- [x] Request a fund from the product page: https://github.com/teamforus/general/issues/363
  - [x] Review design @danrminds  
  - [x] Implement @aghimpu 
- [x] Breadcrumbs: https://github.com/teamforus/general/issues/362 
  - [x] Review design @danrminds  
  - [x] Implement @aghimpu 
- [x] Link to signup page at the end of signupflow: https://github.com/teamforus/general/issues/364
  - [x] Implement @aghimpu 
- [x] Remove ladies page: https://github.com/teamforus/general/issues/365
  - [x] Implement @aghimpu 
- [x] Turn on helpcenter in webshop @GerbenBosschieter 

Should have:
- [x] Fund page redesign (align with other pages): https://github.com/teamforus/general/issues/366   - 
  - [x] Review design @danrminds  
  - [x] Implement @aghimpu 
- [ ] Add success modal after applying for a fund (extra explanation about funds) (needs text/task/design) 
  - [ ] Create concept @jamalv 
  - [ ] Review texts @linda-90 
  - [ ] Review design @danrminds  
  - [ ] Implement @aghimpu 
- [x] Update favicon [pot.svg.zip](https://github.com/teamforus/general/files/5089080/pot.svg.zip)
  - [x] Implement @GerbenBosschieter

**Comment by jamalv** [comment]
- [ ] provider signupflow: organisatienaam ipv bedrijfsnaam: https://www.figma.com/file/8Xc9yR3qpe0C26AfdaZnxH?node-id=1517:109#22593150

**Comment by maxvisser** [comment]
Initial scope estimation is medium; As I see more tasks will be added this IP can become small or big. Probably when  there is a adjust Figma IP which is approved we can estimate this issue better.

**Comment by jamalv** [comment]
<img width="441" alt="Screenshot 2020-08-17 at 09 51 59" src="https://user-images.githubusercontent.com/30194799/90371618-7f4d8580-e06f-11ea-97f9-d2b514377dd0.png">

should be tegoed

**Comment by jamalv** [comment]
notes (discussed with gerben)

Breadcrumbs: https://github.com/teamforus/general/issues/362
Change products to home
Uitleg becomes potjes:  
Potje aanvragen vanaf product page: https://github.com/teamforus/general/issues/363
Doorlink naar aanvraagpagina eind van signup flow: https://github.com/teamforus/general/issues/364
Modal met success (met meer uitleg)
Fund page redesign: https://github.com/teamforus/general/issues/366
Ditch old ladies: https://github.com/teamforus/general/issues/365
