### ISSUE TITLE
POT| Change headerphoto potjeswijzer

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#372]
Figma proposal (seperate file): https://www.figma.com/file/ZfbRjhV8Cd1W83Kvnw7gx0/Potjeswijzer%3A-Header-Photo?node-id=0%3A1

The child makes it to much Kindpakket.

## Task
- [x] make a seperate proposal file @jamalv 
- [ ] get stakeholder feedback on header photos @maartenfv 
- [ ] adjust image to fit dark/white text @Myshelova 
- [ ] add some different headers with text on different resolution sizes to check if it fits. @Myshelova 

Could have: would be nice to have a template where you can a new header image and check multiple screen sizes. @Myshelova

**Comment by maxvisser** [comment]
Suggestions for an image; as it is an header image maybe ask the projectgroup; show some examples from pexels or ask Jan Aaldert

**Comment by maartenfv** [comment]
- Diversity
- Family
- Young old etc. everybody
- Maybe not real people but animation.

**Comment by maartenfv** [comment]
Ook voorleggen aan het panel

**Comment by maxvisser** [comment]
Would be nice if its the same green as logo (or have alot of green in it); I like the colors of the current header image

**Comment by jamalv** [comment]
https://www.figma.com/file/IQ6oy8Up7rBcANPACCydyG?node-id=481:19883#40567985

**Comment by jamalv** [comment]
☝️ @maxvisser

**Comment by maxvisser** [comment]
This image needs to be edited first. As not on all screens it will look the same.

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/93074906-4f50cc80-f685-11ea-970a-6c776930d570.png)
Seems to be less of an issue then I thought.

**Comment by maxvisser** [comment]
I only looked on the smalest resolution. My first instinct thought it was a bad image. After checking it seemed fine. Now after some screenshot of @GerbenBosschieter; Image needs to be changed alot. I would prefer to only start changing / designing images after stakeholder approval

@jamalv I will put this one on hold for now.

**Comment by jamalv** [comment]
I made a separate file and added it to proposals here: https://www.figma.com/file/ZfbRjhV8Cd1W83Kvnw7gx0/Potjeswijzer%3A-Header-Photo?node-id=0%3A1

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/93340342-fde34180-f82c-11ea-91e8-f05c28ec624d.png)

**Comment by maxvisser** [comment]
Cropped out this girl; gerben will add it to code.

**Comment by linda-90** [comment]
Ik heb de header foto met Jan Aldert besproken. Een foto van Pexels vindt hij prima.
De voorbeelden heb ik aan hem laten zien https://www.figma.com/file/IQ6oy8Up7rBcANPACCydyG?node-id=481:19883#40567985

Hij heeft een aantal uitgekozen en die heb ik in dit bestand uitgewerkt: https://www.figma.com/file/ZfbRjhV8Cd1W83Kvnw7gx0/Potjeswijzer%3A-Header-Photo?node-id=84%3A0&viewport=457%2C452%2C0.07808377593755722

Deze voorstellen kunnen we aanstaande donderdag ook aan de projectgroep laten zien.
@jamalv @maxvisser Wat vinden jullie? Zit er een geschikte optie tussen?

**Comment by maxvisser** [comment]
Uit user testing kwam volgensmij het gezin als beste keuze (volgensmij wel een andere versie)

**Comment by jamalv** [comment]
Ik neig dan het meeste naar V4, vind beide kleuren prima. De uitsnede is nog wel wat ruig :P en de resolutie wat laag?

**Comment by linda-90** [comment]
Oké! Ik stel voor dat we ze eerst een versie laten kiezen en dan de definitieve versie maken. Kost me anders teveel tijd om alle afbeelding perfect uit te snijden;)

**Comment by maxvisser** [comment]
Misschien inkoppertje: Heb je wel de high res variant rechten vrij voor
elke?

Op wo 14 okt. 2020 19:35 schreef Linda <notifications@github.com>:

**Comment by maxvisser** [comment]
@linda-90 Could you help with the search for an header image?

**Comment by linda-90** [comment]
@maxvisser Zijn foto's van Pexels, daar kan je ook de high res downloaden.

Verzoek van Westerkwartier is om verschillende headerfoto's te kiezen en deze te laten afwisselen.
Eis is dan dat de tekst en kleur van de afbeeldingen hetzelfde zijn zodat je daar geen issues mee krijgt.

Bijvoorbeeld deze:
<img width="691" alt="Schermafbeelding 2020-12-01 om 12 10 24" src="https://user-images.githubusercontent.com/36952230/100733273-39be8980-33ce-11eb-886c-66e262150ae3.png">

**Comment by maxvisser** [comment]
Heb je links naar de pexel pagina's? De uitknipte versies zijn te lage kwaliteit om te gebruiken; dan maak ik een taak voor alex om de header foto's te maken. Kunnen we wel approval krijgen vanuit de projectgroep voor dat hier externe uren in gaan? (ook op de CR dat we meerdere header fotos gaan gebruiken; maak #290 moeilijker later)

**Comment by maxvisser** [comment]
Persoonlijke mening: foto's vind ik nog steeds heel commercieel ogen en geven geen 'gezellige' uitstraling.

**Comment by linda-90** [comment]
@maxvisser Mee eens. Ik kan de geschikte versies delen en om akkoord vragen. Graag wil ik dan wel duidelijkheid over de meerdere foto's. Kan het wel/niet en waarom.

Tot nu toe zijn er geen betere foto's.

Daarbij komt dat het beter zou zijn als we dit in het CMS hebben staan. De gemeente kan dan zelf een headerfoto of meerdere foto's aanleveren en in het systeem zetten.

**Comment by maxvisser** [comment]
Dat is denk iets voor Jamal om te bepalen. Prioriteit van deze en wanneer het ingeplant kan worden.

**Comment by maartenfv** [comment]
Geen meerdere foto's. Niet voor nu.

**Comment by jamalv** [comment]
Welke foto gaan we gebruiken?

**Comment by jamalv** [comment]
@linda-90?

**Comment by linda-90** [comment]
Deze drie kwamen er het beste uit: https://github.com/teamforus/general/issues/372#issuecomment-736434891 
Ik vind foto 1 het meest passend.

**Comment by maartenfv** [comment]
@maxvisser Kan je de foto die Linda voorsteld plaatsen? @linda-90 hebben we hier een high res versie van?

**Comment by linda-90** [comment]
Hierbij de highres versie: https://www.figma.com/file/IQ6oy8Up7rBcANPACCydyG/Webshop%3A-Potjeswijzer?node-id=600%3A0&viewport=1686%2C-578%2C0.19805704057216644

**Comment by RobinMeles** [comment]
Ik zie dat ik de link niet kan openen van de highres foto in Figma. Ik denk dat ik geen permissie heb. Zou iemand mij dit kunnen geven of zou @linda-90 mij dit plaatje gewoon via Discord kunnen sturen?

**Comment by linda-90** [comment]
@RobinMeles Stuur m wel via Discord:)

**Comment by jamalv** [comment]
Headerphoto has been changed, issue can be re-opened if there is a new one.
