### ISSUE TITLE
Epic: Finalize 4 webshops + align figma library and general webshop

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#375]
## Timeline:
The **must-have** changes should be on a develop branch this week - Then we can review & give feedback  add it to release .15 that we're aiming to stage on wednesday 2nd. The other should-have's can be done during the rest of the sprint.

# Must have
## Webshops
We have 4 new webshops, that should be brought to production quality and prepared for the next release

- [ ] Noordoostpolder: https://dev.forus.io/noordoostpolder/#!/
- [ ] Geertruidenberg: https://dev.forus.io/geertruidenberg/#!/
- [ ] Groningen: https://dev.forus.io/groningen/#!/
- [ ] Potjeswijzer: https://dev.forus.io/potjeswijzer/#!/

## General dev tasks
Some tasks need to be finished and included into the next release:
- [x] Mobile menu: https://github.com/teamforus/general/issues/194
- [x] New navigation: https://github.com/teamforus/general/issues/375#issuecomment-678981395
- [x] Potjeswijzer features: https://github.com/teamforus/general/issues/341 | [branch](https://github.com/teamforus/forus-frontend/tree/features-potjeswijzer)

## Figma links:
* [Noordoostpolder](https://www.figma.com/file/pUWeZwelwsJK8W58ZGip9r/Noordoostpolder?node-id=658%3A88)
* [Geertruidenberg](https://www.figma.com/file/qWrX7jmcCLjrFEMWe6FjDX/%F0%9F%8C%8D-Webshop-Geertruidenberg?node-id=317%3A20206)
* [Groningen](https://www.figma.com/file/LOei9CO8mj4lshcCHQvTBz/Webshop-Groningen?node-id=1%3A2)
* [Potjeswijzer](https://www.figma.com/file/IQ6oy8Up7rBcANPACCydyG/Potjeswijzer.nl?node-id=2%3A7819)

# Should have
## Design tasks
- [x] Merge new navigation and "potjeswijzer" changes into library @danrminds 
- [x] Resolve conflicts with duplicate pages in Figma @Myshelova @aghimpu  (https://www.figma.com/file/7lQX9ZRpJW3ZTCtEosAMzs/Webshop?node-id=855%3A19457)
- [ ] Review alignment of code and webshop library @danrminds @Myshelova @GerbenBosschieter @jamalv 

## Alignment task
- [ ] Align the **general** webshop with the library in Figma **Note:** We can make a few minor fixes, but scope should be kept as small as possible. The goal is alignment, not visual improvements (yet :))
- [ ] When making changes, we should test/review all implementations (to make sure there's no weird CSS bugs)

* https://dev.forus.io/nijmegen/#!/
* https://dev.forus.io/berkelland/#!/
* https://dev.forus.io/oostgelre/#!/
* https://dev.forus.io/westerkwartier/#!/
* https://dev.forus.io/kerstpakket/#!/
* https://dev.forus.io/noordoostpolder/#!/
* https://dev.forus.io/geertruidenberg/#!/
* https://dev.forus.io/potjeswijzer/#!/
* https://dev.forus.io/groningen/#!/

**Comment by GerbenBosschieter** [comment]
# Webshop improvements (navigation)

In addition to the goal of finalising the webshops we would like to include the new navigation as well.
The new navigation wil influence all of the webshops and we have some desires of how to implements this.

- Good baseline in the common 
- As much variables we cann add in the vars.scss
- As little a possible extra css files for navigation per implementation

## Goals
- As much as css possible in the common
- The code quality @dev-rminds and @aghimpu  you desire
- Easy to change if there is a new implementation (variables, not to much css navigation.scss files)
- No navbar should be be fixed anymore
- On mobile the navbar should be as the mobile footer branch

#### Current state:
I've already started with a branch where I included the the above mentioned desires and goals. Only problem is that I am not sure if @dev-rminds @aghimpu  agree with the way I did it. So Please take a quick look how I did it, continue with it our start over and make it better.

### Proposals / designs
[Baseline for the navigation:](https://www.figma.com/file/FMhzCEMbbTGiPjAmOvnTQn/Update-webshop-menu-bars?node-id=0%3A1) (use the one Will Smith is presenting ;)

This design can be used for every webshop as a baseline. I can imagine that some of the webshop do need an extra css file to make it work for their specific design.
- Common
- Oost Gelre
- Berkelland
- Winterswijk
- Noordoostpolder

Webshops that probably need a additional navigation.scss (click on the link to see a example, it should be visually as close as the links below)
**Groningen:** https://dev.forus.io/groningen/#!/
**Nijmegen:** https://dev.forus.io/nijmegen/#!/
**Westerkwartier:**  https://dev.forus.io/westerkwartier/#!/

**Branch:** [develop.webshop-improvements-navigation ](https://github.com/teamforus/forus-frontend/tree/develop.webshop-improvements-navigation)

**Comment by maartenfv** [comment]
- Spacing of header Needs more whitespace so it will look better
- Change the title to something better @linda-90 Please check met Trees
- Check the text met Tress @linda-90 Please check met Trees
- Remove lines as they make it less clear.

**Comment by maartenfv** [comment]
Flip links they are not correct 
![image](https://user-images.githubusercontent.com/30211022/91049181-12149400-e61d-11ea-8fc9-a62639e990eb.png)

**Comment by Myshelova** [comment]
For a point that I mentioned, I suggest choosing pages with Atomic design

**Comment by jamalv** [comment]
@danrminds I'm un-assigning me and gerben for now; as I think there's nothing we can do at this point; if there's any questions please let us know and re-assign! :D

**Comment by Myshelova** [comment]
Feedback for new webshops.

1. Webshop: https://dev.forus.io/noordoostpolder/#!/
a) Really small logo on a big header. + the position at the main page is shifted down
- Main
￼
![image](https://user-images.githubusercontent.com/22478043/91175216-c2979c00-e6e0-11ea-9d93-8313cdddc483.png)

- Other pages 
￼
![image](https://user-images.githubusercontent.com/22478043/91175226-c62b2300-e6e0-11ea-8496-73a8551db06e.png)

b) I don’t recommend using different font styles for the same buttons
￼
![image](https://user-images.githubusercontent.com/22478043/91175236-ca574080-e6e0-11ea-9617-6cf8da6e70b8.png)

2. Webshop https://dev.forus.io/noordoostpolder/#!/ https://dev.forus.io/groningen/#!/
a)Both headers with navigation invisible from first glance
My suggestion makes a text more visible and thinks about how to make this block more visible too.
￼
![image](https://user-images.githubusercontent.com/22478043/91175252-d0e5b800-e6e0-11ea-924e-51aa4bac9394.png)
![image](https://user-images.githubusercontent.com/22478043/91175267-d3e0a880-e6e0-11ea-8bc9-431b082957b7.png)

b)At the Groningen webshop it’s also difficult to recognise with the component are important and where user can find navigation because here is three opposite colours (black, grey and white) and together they are making a small compositional collapse

![image](https://user-images.githubusercontent.com/22478043/91175312-e1962e00-e6e0-11ea-83c0-2f42de952316.png)

￼
c) I also highly recommend making a fixed header for both of webshops. Currently, they’re hiding on scroll

3. Webshop https://dev.forus.io/groningen/#!/
This footer makes my eyes cry:) 
I would suggest changing colour because it’s super hard to look at this red block with white text and white background on a site

I like the red colour but we can’t find a better way of using it
￼
![image](https://user-images.githubusercontent.com/22478043/91175350-ef4bb380-e6e0-11ea-96fa-d09ef7d70e74.png)


4. Webshop https://dev.forus.io/potjeswijzer/#!/
I like both colours but together they are looking too bright. And the login button is not visible. Maybe we will use only one colour here?
￼
![image](https://user-images.githubusercontent.com/22478043/91175363-f377d100-e6e0-11ea-9c46-095f94da3bc8.png)

**Comment by jamalv** [comment]
@Myshelova regarding potjeswijzer; there is a new version based on the new header: https://test.potjeswijzer.nl/backup/#!/

login: potje
password: voetbal2020

**Comment by jamalv** [comment]
regarding the logo of noordoostpolder; we are aware of this issue, it will be fixed on new dev version :)

I expect new dev version will be there on thursday (if this is possible for @aghimpu), that means we can better review then :)

**Comment by jamalv** [comment]
about footer of groningen; this is their own website; we can look at it for inspiration about their brand identity: https://gemeente.groningen.nl/

**Comment by jamalv** [comment]
@Myshelova, I just added some comments on figma regarding feedback from clients on potjeswijzer :)

**Comment by jamalv** [comment]
Separate tasks have to be created be created for this. This issue can be closed when that is done.

**Comment by maxvisser** [comment]
Checked all stuff in this issue; Lets close it.
