### ISSUE TITLE
PISP (BNG) connection: Research

### ISSUE THREAD

**Issue by maartenfv** [teamforus/general#381]
# General info
details: internal [drive](https://drive.google.com/drive/folders/1k4-19lmvP4CW_nRXxJbDycHupekW6TsR)

## Current situation
We are currently using bunq to make payments. 

## Desired situation
We want to use the BNG PSD2 API connection to make payments

Sandbox: https://api.xs2a-sandbox.bngbank.nl/
Example payment initiation: https://api.xs2a.bngbank.nl/developer-portal/service-documentation/payment-initiation-service

# Project checkpoints and deliverables:
**Note:** dates are guidances and will updated at each checkpoint.

### Checkpoint 1: Kick-off on 26 oktober

Deliverables fase 1: 9th november (2 weeks).
- [ ] Technical proof of concept: perform bulk payment initiation @max @valentin
- [ ] Implementation plan: Todo’s for each municipality and timeline @linda @maarten
- [ ] Development scope: User story map and low-fidelity prototypes @jamal @lena
- [ ] Funding: Quotation of full implementation cost (development time) @dan @valentin

### Checkpoint 2: Presentation: Phase 1 results - 9th november.
- [ ] Demo: Technical POC @max @valentin
- [ ] Presentation: implementation plan @linda @maarten
- [ ] Presentation: user story map en low fidelity figma prototypes @jamal @lena
- [ ] Presentation: updated planning: @maarten @jamal

**Deliverables of Phase 2:** 7th of december (4 weeks)
- [ ] Code is on dev, ready for staging on December 13th @valentin
- [ ] Configuration dependencies received and tested @linda @maarten 
- [ ] Funds are ready on the BNG accounts of municipalities @linda @maarten 
- [ ] Working instructions shared and employees are trained @gerben @michael

### Checkpoint 3: Ready for takeoff - 6th december
- [ ] Demo of BNG transactions on dev @maxvisser @valentin
- [ ] Status update implementation @linda @maarten
- [ ] Status update training of municipalities @gerben @michael

**Deliverables phase 3:**
- [ ] Deploy and launch on december 20th

### Checkpoint 4: Reflection and retrospective - 11th of January
- [ ] Retrospective

**Comment by jamalv** [comment]
@maxvisser could you already create the tasks for this epic?

**Comment by maxvisser** [comment]
I can for the research task for dev-rminds. But before starting research I would first create a task to find API documentation and SDK (where to get the PHP SDK; is there one?).

**Comment by maxvisser** [comment]
Created a task for this

**Comment by jamalv** [comment]
When looking for documentation I think we have to search for "XS2A (Access to accounts) Interface" the BNG docs can be found over at, maybe there are other docs as well: https://api.xs2a.bngbank.nl/developer-portal/service-documentation/payment-initiation-service#initiatepayment

I'm not sure if there is any SDK. I think @SjoerdHilhorst, you spent a bit of time recently looking in to this? Did you find any interesting / relevant info? Could you post it here?

**Comment by maxvisser** [comment]
When is deadline for research; my proposal is to start on this after all other must haves are done. Whats priority in contrast to other must haves? As in do we plan this before #359 for example or before should haves from implementation which go live on 1 oct / 1 nov

**Comment by jamalv** [comment]
Yes, those must-haves have priority over this one. But, by doing research (2 days for example) will help us with sprintplanning for the rest of the year earlier on, so the sooner we can plan that in a sprint, the better off course. But we first need to make sure the 1 oct / 1 nov implementations will go well.

**Comment by maxvisser** [comment]
Ok! We want to do this one this year? This is a really big scope; probably takes multiple sprint; (I would plan this for Q1 next year and first focus on #431 and maybe aswell fix some other big transaction issues #239)

If you ask me to estimate it I think it would take more then 2 days to setup the API without SDK; we could ask @dev-rminds / @danrminds for an estimate. As we don't really have yet a good planning for next couple of sprints I can't really tell where and when to plan it. (a better estimation of the research needs to take place); An option could be to do this research even later.

Also we should set a clear goal for such a research to better estimate how much time is needed. Which questions do want answer on?

**Comment by maartenfv** [comment]
This issue has been open for a while. We need to build the connection before the end of the year. Clear goal: SDOA wants to go live with BNG on Jan 1 st.

**Comment by maartenfv** [comment]
@jamalv Could you give an update?

**Comment by maxvisser** [comment]
as @dev-rminds needs to do the research and is currently busy with finishing three other projects; no progress has been made. If it is still possible I would vote against implementing this on 1st of januari. Too risky as we probably need to rush implementation and testing

**Comment by maartenfv** [comment]
@maxvisser We are still planning to implement this before 1 January 2021 because the municipalities are getting into trouble using bunq. @jamalv We should plan and discuss this with @danrminds and @dev-rminds

**Comment by jamalv** [comment]
I have had a discussion about this with @danrminds, we discussed starting research / a POC before @dev-rminds starts, to make sure the ball is already rolling as much as possible. 

@danrminds could you use this issue to give some status updates when you have them?

**Comment by maxvisser** [comment]
Planned to start working on this in sprint 2020-Q4-S2 | Weeks 43+44

**Comment by jamalv** [comment]
@maartenfv are there any transaction costs? :)

**Comment by jamalv** [comment]
Got a workaround for 500 errors, Valentin will finish prototype.
