### ISSUE TITLE
Update and extend testing paths

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#430]
### User Story
As a client I want to have testing paths for my requirements so that I can accept the results.

#### Acceptance criteria
There should be testing paths that cover the core [acceptance criteria](https://docs.google.com/document/d/1sp0dghXm_tOEOwDGM_Y8NrZHioGqx27U0b068D0X73o/edit#)

working doc: [internal](https://docs.google.com/document/d/1sp0dghXm_tOEOwDGM_Y8NrZHioGqx27U0b068D0X73o/edit#)

## Tasks
- [ ] Create planning for creating and executing testing paths with client @maartenfv 
- [ ] Update this issue with refined subtasks for testing moments and test criteria @jamalv 
- [ ] Create separate tasks for the tasks in this epic @maxvisser 

### Subtasks (draft - should be refined & broken up into separate issues with assignees etc.)
- [ ] Proof of concept
	- [ ] Create 1 testing path on an acceptance criteria @maxvisser 
	- [ ] Load testing path and criteria into testing tool @maxvisser 
	- [ ] Check results and validate with client that this is sufficient @maartenfv 
- [ ] Test moment 1
	- [ ] Create all testing paths for this testing moment scope
	- [ ] Load testing paths for testing moment into tool
    - [ ] Execute tests with client and log results and findings
	- [ ] Add results and findings to the backlog
	- [ ] Apply labels to tasks on backlog (priority @jamalv, scope @maxvisser)
- [ ] Test moment 2
	- [ ] Create all testing paths for this testing moment scope
	- [ ] Load testing paths for testing moment into tool
    - [ ] Execute tests with client and log results and findings
	- [ ] Add results and findings to the backlog
	- [ ] Apply labels to tasks on backlog (priority @jamalv, scope @maxvisser)
- [ ] Test moment 3
	- [ ] Create all testing paths for this testing moment scope
	- [ ] Load testing paths for testing moment into tool
    - [ ] Execute tests with client and log results and findings
	- [ ] Add results and findings to the backlog
	- [ ] Apply labels to tasks on backlog (priority @jamalv, scope @maxvisser)
- [ ] Test moment 4
	- [ ] Create all testing paths for this testing moment scope
	- [ ] Load testing paths for testing moment into tool
    - [ ] Execute tests with client and log results and findings
	- [ ] Add results and findings to the backlog
	- [ ] Apply labels to tasks on backlog (priority @jamalv, scope @maxvisser)
- [ ] Test moment 5
	- [ ] Create all testing paths for this testing moment scope
	- [ ] Load testing paths for testing moment into tool
    - [ ] Execute tests with client and log results and findings
	- [ ] Add results and findings to the backlog
	- [ ] Apply labels to tasks on backlog (priority @jamalv, scope @maxvisser)

**Comment by maxvisser** [comment]
Maybe close this one in favor all the issues in implementation?

**Comment by maartenfv** [comment]
@maxvisser can we merge? Are there steps we should add to the other issues?

**Comment by jamalv** [comment]
done
