### ISSUE TITLE
Acceptance test: proof of concept

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#443]
## Goal
The goal of this task is to define how we want to test with Groningen by first doing the full test cycle with as small a scope as possible, before we start testing the full PVE.

## Definition of done
- [x] Internal acceptance of method of testing for the proof of concept & the other criteria can be tested in the same way. 

All the criteria can be found here: https://docs.google.com/document/d/1sp0dghXm_tOEOwDGM_Y8NrZHioGqx27U0b068D0X73o/edit#heading=h.ukqlie3f2o0b

## Tasks
- [x] [Answer question about language, internal/external](https://docs.google.com/document/d/1sp0dghXm_tOEOwDGM_Y8NrZHioGqx27U0b068D0X73o/edit?disco=AAAAKPenKyA) @maartenfv 
- [x] Pick one criteria for proof of concept @maxvisser ([D1, D2](https://docs.google.com/document/d/1sp0dghXm_tOEOwDGM_Y8NrZHioGqx27U0b068D0X73o/edit#heading=h.lm2a7doxsm41))
- [x] Add the path to testquality @maxvisser
- [x] Internally go trough testpath and review @jamalv 
- [x] Create issues / CR's from the findings @jamalv 
- [x] Check CR's and plan in @maxvisser
- [ ] Create report in testquality @maartenfv 
- [ ] Go trough testing poc with client @jamalv with Bas?
- [ ] Create issues / CR's from the findings with client @jamalv 
- [ ] Check CR's and plan in @maxvisser

**Comment by jamalv** [comment]
We will fill the test scenario's in english and translate the bullets

**Comment by maartenfv** [comment]
https://github.com/teamforus/implementation/issues/302

**Comment by maxvisser** [comment]
https://github.com/teamforus/development/blob/master/.github/ISSUE_TEMPLATE/test-scenario---3---sign-up-flow-provider---url-filter.md

**Comment by maxvisser** [comment]
added D1 to testquality


Project: Testing
Test plan: Acceptance testing
Test plan run: Release vX.X.X
![image](https://user-images.githubusercontent.com/10818702/93339776-451d0280-f82c-11ea-8fa2-b6d8f116e15f.png)

Test plan bestaat uit test 'suites' -> flows/scenario's in applicatie
die wellicht op verschillende manieren kunt bereiken (happy flows, alternative paths etc)
![image](https://user-images.githubusercontent.com/10818702/93339800-4cdca700-f82c-11ea-9744-820f623fcfe7.png)

dat zijn de test cases
dus bijv. Provider signupflow aanmelden via Me-app en scannen test transactie
Maar ook aanmelden via flow (geen me-app) en URL filters
Aan die test cases kun je dan Requirements hangen zoals "minimaal de volgende gegevens: Organisatiecode, naam, telefoonnummer, e-mail, website, KvK-nummer, IBAN-nummer, Logo."
Ik heb een test run gedaan en zelfs een defect gevonden (een echte :D)

dan zou D1 drie requirements zijn:
- Nieuwe aanbieders kunnen zichzelf aanmelden op het systeem 
- Minimaal volgende gevens zijn verplicht: Organisatiecode, naam, telefoonnummer, e-mail, website, KvK-nummer, IBAN-nummer, Logo.
- Een aanmelding van een aanbieder moet door een medewerker worden geverifieerd.

**Comment by maxvisser** [comment]
Opsplitsen van bepaalde test casuses kan helpen met reusability van de steps. Bijv login kun je dan aan meerde suites toevoegen.

**Comment by maxvisser** [comment]
Requirements moeten issues zijn dus ik heb een testing repo aangemaakt en issues daarin gezet voor de drie requirements.

**Comment by jamalv** [comment]
@maxvisser let's go trough the testpath once together?

**Comment by maxvisser** [comment]
Went through one with Jamal decided to go ahead with Sjoerd his setup. We can export all test cases from this project and reuse them later.

**Comment by maxvisser** [comment]
@maartenfv Was the report created?
@jamalv Did you check the setup with Bas?

**Comment by jamalv** [comment]
@maartenfv let's go trough this one together, in preparation for the testing with Groningen. Then we can also decide how(/if) we'd like to go trough this with bas before the testing moment itself.

**Comment by jamalv** [comment]
Discussed with maarten that external stakeholder review is not required on the poc, internal review will suffice.

So, DoD is changed, making the scope smaller. Closing this issue.
