### ISSUE TITLE
POW | Potjeswijzer.nl webshop

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#45]
### Organisational context
Every charitable organisation has their own website and processes. For people in need, this makes it hard to get an overview of what's available. The goal of this webshop is for multiple sponsors, validators to work together to offer their services in one place.

### Technical context
Our current webshop offers the functionality that is needed. We have had many discussions with end users about this webshop and gathered a lot of feedback on it.

**Links:** 

Webshop configuration (DEV):
https://docs.google.com/document/d/16Y5z_qrxQxCDI_YB3J02WLOW2G0rJKq3nwt3oLM_haI/edit?usp=sharing

Figma MVP: https://www.figma.com/file/IQ6oy8Up7rBcANPACCydyG/Potjeswijzer.nl?node-id=0%3A1

Figma initial concept: https://www.figma.com/file/IQ6oy8Up7rBcANPACCydyG/Potjeswijzer.nl?node-id=2%3A7838

## Tasks
- [x] Make MVP using our current templates and the branding of potjeswijzer.nl
  - [x] Update content of the Figma MVP @jamalv @Myshelova 
    - [x] Update menu @Myshelova 
	- [ ] Update header @Myshelova 
	- [ ] Update texts / content @jamalv (@linda-90 review)
  - [x] Finish the library templates of the current design @Myshelova 
  - [x] Develop webshop @aghimpu 
  - [x] Stage webshop @maxvisser 
- [ ] Make prototype of new version > iterate and incrementally implement it @jamalv @Myshelova 

## Inspirational materials
A student group came up with a proposal that we can use as inspiration. We can change it up if we want to, and we wil (initially) stick to our current templates, but we like this direction and the reactions are good so we would like to follow it.

[VanArmnaarBeter-eindrapport.pdf](https://github.com/teamforus/general/files/4368116/VanArmnaarBeter-eindrapport.pdf)

<img width="507" alt="Screenshot 2020-03-23 at 09 31 26" src="https://user-images.githubusercontent.com/30194799/77298701-9c15a500-6ceb-11ea-825f-23bc6c2ec5d6.png">

<img width="575" alt="Screenshot 2020-03-23 at 09 31 13" src="https://user-images.githubusercontent.com/30194799/77298791-bd769100-6ceb-11ea-9271-90af88e1207d.png">

**Comment by maxvisser** [comment]
As you now have clear solution in the proposal, did you consider any other option for design language? Also we plan this in time; who wants to be informed and when.

**Comment by maxvisser** [comment]
heb de vragen in de gDocs gezet (configuratie dev)

**Comment by maxvisser** [comment]
@jamalv I think this epic should contain a DoD maybe we should do a quick session about what needed

**Comment by maxvisser** [comment]
Create seperate change request for:
- a new logo for Potjeswijzer
- Webshop Sign-up page needs some love

**Comment by jamalv** [comment]
change request for logo: https://github.com/teamforus/general/issues/241

**Comment by jamalv** [comment]
@maxvisser I think this issue can be considered done; it is a bit too big and vague. We should create seperate issues for the things that are needed still. Probably from the usertests we will have plenty :)

About the webshop sign-up page there is this issue: https://github.com/teamforus/general/issues/135

**Comment by maxvisser** [comment]
I agree to keep DoD correct though we could decide to keep this one open until there is actually a potjeswijzer.nl webshop (as currently we don't host one yet)

**Comment by jamalv** [comment]
Well, to bring it to production, I assume the WK one needs to go offline. Do you want to keep this open until then?

**Comment by jamalv** [comment]
I mean, we can, I'm definitely not against it, I'm fine either way :)

**Comment by maxvisser** [comment]
Well it occured to me that probably we should still have issues for the things on this list with a comment on why it is not deployed yet https://github.com/teamforus/itsm/issues/228

Somewhat the same with this one. Development is 'finished' but its not used on production yet.

**Comment by maartenfv** [comment]
Can we do a language check on this one?

**Comment by maxvisser** [comment]
https://www.figma.com/file/IQ6oy8Up7rBcANPACCydyG/%F0%9F%91%A9%E2%80%8D%F0%9F%92%BBPotjeswijzer.nl?node-id=42%3A10567&viewport=816%2C3799%2C0.24384088814258575
this is figma; its a normal webshop without alot of texts (now alot of texts are also user configurable) So I am not sure what you can check.

**Comment by jamalv** [comment]
MVP is on dev (test.potjeswijzer.nl) > superseding this issue with this one for specific improvements: https://github.com/teamforus/general/issues/341

**Comment by jamalv** [comment]
☝️ reasoning is as follows; from a development perspective it will be much clearer to create seperate tasks for fixes / improvements, as the basis (MVP) is there.


The next steps (implementation, configuration + deployment to staging / production should be a specific (ITSM / Implementation) task when there are concrete plans for that.
