### ISSUE TITLE
Onboarding new teammembers

### ISSUE THREAD

**Issue by danrminds** [teamforus/general#780]
**Time tracking**
This issue is used for time tracking when conducting onboarding activities.

**Onboarding**
Onboarding is the process through which organizations equip new employees with the knowledge and skills they need to succeed at their jobs.

**Comment by jamalv** [comment]
We discussed this issue today with dan and max. Next to using this issue for time tracking, we should also start on a strategy as Forus on how we onboard new developers. 

- [ ] Writing abstract documentation about the platform
- [ ] Updating getting started documentation
- [ ] Updating the api documentation
