### ISSUE TITLE
Write / update documentation

### ISSUE THREAD

**Issue by jamalv** [teamforus/general#788]
Learn more about change requests here: https://bit.ly/39CWeEE

### Change description
As a new developer I would like to be able to do self-study to learn how to contribute, before I get training / support from the core developers.

## Tasks
- [ ] Index what documentation is already there
- [ ] Update outdated documentation
- [ ] Decide how to publicise documentation (github/postman/manuals/support.forus etc)
- [ ] Extend the documentation to make it complete
