### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by danrminds** [teamforus/general#807]
Documentation proposal: https://docs.google.com/document/d/1WrPrKIJbwfAs2NSwcQ6zXEYD7D0HBT8IJev8cOKDLP4/edit

Documentation drive: https://drive.google.com/drive/folders/0AF-Tbb0C4f1DUk9PVA

## Tasks
- [x] Index what documentation is already there
- [x] Specify requirements for documentation
- [ ] Update (outdated) documentation into google shared drive
- [ ] Decide how to publicise documentation (github/postman/manuals/support.forus etc)
- [ ] Extend the documentation to make it complete
- [ ] Write a simple and useful documentation procedure that every developer will follow
- [ ] Implement procedure by letting everybody know (Write an email with link to instructions)

**Comment by danrminds** [comment]
@jamalv Can you link the file here?

**Comment by jamalv** [comment]
@danrminds done 👍
