### ISSUE TITLE
Project: ANB (project-31)

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#94]
@jamalv commented on [Tue Jan 21 2020](https://github.com/teamforus/development/issues/330)

## Context
<details><summary>Click to read context about the project</summary>

## Context

We are currently doing a project which is called "Van arm naar beter" which means "From poor to better". It is aimed at connecting the organisations/charities that are working together in and around the municipality of [Westerkwartier](https://en.wikipedia.org/wiki/Westerkwartier_(municipality))

There are twelve of parties working together that have the role of sponsor (charities), validator (volunteers, charities and professionals), provider (local shops) and requestor (working groups of people that give us feedback). You can view the whole list of organisations [here](https://www.vanarmnaarbeter.nl/vanarmnaarbeter/inhoud_41331/item/deelnemende-organisaties_4103.html) 

The municipality got a subsidy from the Ministry of Internal Affairs for that funds this project to to get all the organisations to work together using Forus.
</details>

## Goals

The main goal of the project is to create a new webshop (design+frontend) and implementation of the platform, where the 12 parties can work together in their roles, the webshop is aimed to be very general.

## Way of working
We start with whitelabeling and sharing our current designs (webshop, dashboards and app) and then discuss and itteratevely improve the designs and work on branding a webshop for this particular project
* Create a white labeled webshop & create and share a prototype for feedback
* Add the dashboards to figma & create and share a prototype for feedback
* Discuss and iterate together with the customer
* Start implementing iterations after customer and developer approval  

## Tasks
All issues that are related to this project should be labeled [project-31](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+archived%3Afalse+sort%3Aupdated-desc+label%3Aproject-31+)

- [x] Pentest
- [x] Fix pentest findings
- [ ] After deciding on name and branding; create webshop in new branding
- [ ] Whitelabel MVP of webshop to discuss with customer https://github.com/teamforus/development/issues/318
- [x] Create Figma prototype of dashboards and app to gather feedback and improve https://github.com/teamforus/forus/issues/1193, https://github.com/teamforus/development/issues/269, https://github.com/teamforus/forus/issues/1310, https://github.com/teamforus/forus/issues/1311,
- [ ] Comply to WCAG2.0 https://github.com/teamforus/implementation/issues/35
- [ ] Epic: External validation https://github.com/teamforus/development/issues/344
- [ ] Manage (CRUD) your attributes (on webshop and in me app) https://github.com/teamforus/development/issues/345
- [x] Sponsor signup flow https://github.com/teamforus/development/issues/125
- [x] Provider signup flow https://github.com/teamforus/forus/issues/867
- [x] Requestor signup flow https://github.com/teamforus/development/issues/118
- [x] Validator signup flow https://github.com/teamforus/development/issues/343
