### ISSUE TITLE
Epic: Voucher generator fixes

### ISSUE THREAD

**Issue by maxvisser** [teamforus/general#96]
@jamalv commented on [Wed Jan 22 2020](https://github.com/teamforus/development/issues/333)

## Context
We are currently working hard at implementing DigiD. There is a chance we will miss the deadline. The muncipality wants to use the voucher generator as a backup plan. 

There is also a muncicipality that wants to use the voucher generator to be able to assign multiple (seperate) vouchers for the same fund. They want to assign each child a seperate voucher. Currently with the voucher generator this is possible, but there are risks involved.

This issue is about identifying and solving the risks and to get the voucher generator ready to be used for such usecases. 

## Issues:
- [x] Duplicates warning https://github.com/teamforus/forus/issues/1386
- [ ] Update email https://github.com/teamforus/forus/issues/1384
- [ ] Send after first login https://github.com/teamforus/forus/issues/1385
- [x] Top up / new voucher https://github.com/teamforus/forus/issues/1389
- [ ] Show bounces https://github.com/teamforus/forus/issues/1387
- [ ] DigiD migration preperation https://github.com/teamforus/forus/issues/1388

---

@jamalv commented on [Wed Jan 22 2020](https://github.com/teamforus/development/issues/333#issuecomment-577171248)

Don't precreate identies in bulk (disable bulk) until all issues above are fixed.

---

@maxvisser commented on [Tue Jan 28 2020](https://github.com/teamforus/development/issues/333#issuecomment-579388238)

in this issue we forgot about emails that exist but are wrong; we need some policy on how to deal with vouchers that are used by not the owner;

we currently already have this problem when people dont have acces to their mailbox anymore; this results in pretty big support issues as there is no way for us to verify who is the owner.

so only option i see is to or really communicate 'we dont support deletion of voucher' 'you cant undo these kinds of mistakes'; or allow sponsors to expire vouchers

**Comment by maxvisser** [comment]
duplicates warning should be on production on 17 August

**Comment by jamalv** [comment]
Closing this epic in favour of the seperate issues (epic is no longer relevant) - and this is a stale issue
